search_tweets_api:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/30day/30day.json #replace with "fullarchive" to change to the fullarchive endpoint
  consumer_key:
  consumer_secret:
